AllCops:
  TargetRubyVersion: 2.5.0
  DefaultFormatter: fuubar
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'app/views/**/*.axlsx'

Layout/HashAlignment:
  Enabled: true
  EnforcedLastArgumentHashStyle: always_ignore

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/ExtraSpacing:
  AllowForAlignment: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Style/BlockDelimiters:
  Exclude:
    - spec/**/*_spec.rb

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*.rb'

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/GuardClause:
  Enabled: false

Style/RedundantSelf:
  Enabled: false
